### ISSUE TITLE
getting erros when i try to post my ad on certain servers

### ISSUE THREAD

**Issue by paul38752** [XtramCZ/auto-advertise-js#6]
> A message was sent to "⏫・above-100-servers" in "🧸Teddy Bear Advertisments & Nitro Giveaways"
 > A message was sent to "🏠・community-servers" in "🧸Teddy Bear Advertisments & Nitro Giveaways"
 > A message was sent to "🏹・advertising-war" in "🧸Teddy Bear Advertisments & Nitro Giveaways"
 > A message was sent to "🎆・entertainment-servers" in "🧸Teddy Bear Advertisments & Nitro Giveaways"

console.log(color.red(` > There was a problem sending a message to "${channel.name}" in "${channel.guild.name}"`))
                                                                                    ^

TypeError: Cannot read properties of undefined (reading 'name')
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

then the script stops completely

**Comment by XtramCZ** [comment]
Can you tell me what is the channel name? Meanwhile, disabling debug mode should fix it.

**Comment by paul38752** [comment]
ok i think disabling debug fixed it
also the channel id name was server advertising from golden advertising

**Comment by Kephronic** [comment]
I just finded a way to fix it "${channel?.name}" "${channel?.guild?.name}"
You just can add ? before the . in the variables

**Comment by XtramCZ** [comment]
@Kephronic IIRC, Your fix only works when the channel is not found, but in that case, it's already thrown an error. However, if you put the "?" like this: ${channel.name?} it should work - it checks if the channel.name exists

**Comment by paul38752** [comment]
im still getting errors on my main advertising account it works fine but on my alts its having issues and yes i have debug mode disabled

**Comment by XtramCZ** [comment]
Same error?

ne 2. 4. 2023 v 18:44 odesílatel paul38752 ***@***.***>
napsal:

**Comment by XtramCZ** [comment]
Same error?

**Comment by paul38752** [comment]
@XtramCZ yes

**Comment by XtramCZ** [comment]
Try the new fix

**Comment by paul38752** [comment]
i think it made things worse

**Comment by XtramCZ** [comment]
What problems?

**Comment by paul38752** [comment]
> There was a problem sending a message to "🕑┇6-hour" in "Royal Advertising | Nitro Giveaway"
 > There was a problem sending a message to "⚡┇unlimited-advertising" in "Royal Advertising | Nitro Giveaway"
 > There was a problem sending a message to "🏡┇community-servers" in "Royal Advertising | Nitro Giveaway"
 > There was a problem sending a message to "🎮┇gaming-servers" in "Royal Advertising | Nitro Giveaway"
 > There was a problem sending a message to "⚡┇unlimited-advertising" in "Community Advertising & Nitro Giveaways!"
 > There was a problem sending a message to "💬┇discord-servers" in "Community Advertising & Nitro Giveaways!"
 > There was a problem sending a message to "🤹┇community-servers" in "Community Advertising & Nitro Giveaways!"
 > There was a problem sending a message to "🕝┃60-seconds" in "Super Advertisement"
 > There was a problem sending a message to "🕝┃1-hour" in "Super Advertisement"
 > There was a problem sending a message to "🕝┃2-hour" in "Super Advertisement"
 > There was a problem sending a message to "🕝┃6-hour" in "Super Advertisement"

im getting this on all my accounts now the script works for a while but then once it reaches a certain server it starts getting error after error and then crashes

**Comment by XtramCZ** [comment]
I updated the code, however, I think you have problems sending to channels because you are rate limited by Discord - you post to too many channels at once, I don't know If I can fix that, maybe with more delay between sending the message. Try changing the number on line 61: `await sleep(1000)` to something bigger, like `await sleep(2500)` or even bigger, if that works i will implement it into config

**Comment by paul38752** [comment]
i figured out that some of the errors were caused by a few of the channels being deleted but i will update you on if i get issues again

**Comment by XtramCZ** [comment]
Okay, I will close this issue for now. Contact me if you ever encounter any issues, thanks for helping improve the tool :)
